In [1]:
!pip install numpy

In [3]:
import numpy as np

In [5]:
from numpy import *

In [12]:
x = linspace(-pi,pi,5)
print(x)
y = linspace(-pi,pi,5)
print(y)

[-3.14159265 -1.57079633  0.          1.57079633  3.14159265]
[-3.14159265 -1.57079633  0.          1.57079633  3.14159265]


In [22]:
Z = array([[-3.14159265, -1.57079633, 0, 1.57079633,  3.14159265],[-3.14159265, -1.57079633, 0, 1.57079633,  3.14159265]])
print(Z)
Z.shape

[[-3.14159265 -1.57079633  0.          1.57079633  3.14159265]
 [-3.14159265 -1.57079633  0.          1.57079633  3.14159265]]


(2, 5)

In [6]:
import cmath
x,y = symbols ('x, y')
def F(x,y):
    return exp(1i*y) + 2*exp(-1i*y/2) * cos(3**0.5/2*x)

SyntaxError: invalid syntax (Temp/ipykernel_72860/1663844038.py, line 4)

In [1]:
from sympy import *
import cmath
x,y = symbols ('x, y')
F = (1*exp(1i*y) + 2*exp(-1i*y/2) * cos(3**0.5/2*x))
result = F.subs({x:-3.14159265, y:-3.14159265})
print(result)

SyntaxError: invalid syntax (Temp/ipykernel_76404/4080316301.py, line 4)

In [2]:
def F1(x,y):
    return exp(-1i*y) + 2*exp(1i*y/2) * cos(3**0.5/2*x)

SyntaxError: invalid syntax (Temp/ipykernel_76404/998327153.py, line 2)

In [3]:
A = array([[0,F],[F1,0]]
M = matrix(A)
M1= conjugate(M)

SyntaxError: invalid syntax (Temp/ipykernel_76404/3655771340.py, line 2)

In [7]:
def plot_F:
    F = exp(1i*y) + 2*exp(-1i*y/2) * cos(3**0.5/2*x)

SyntaxError: invalid syntax (Temp/ipykernel_72860/1308743725.py, line 1)